USE [easyxms]
GO

/****** Object:  Table [dbo].[PUBLS]    Script Date: 28.06.2016 16:10:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PUBLS](
	[PUBL_ID] [int] NOT NULL,
	[PUBL_NAME] [nvarchar](100) NULL,
	[PUBL_DESC] [nvarchar](max) NULL,
	[PUBL_CREATED_BY] [int] NULL,
	[PUBL_CHANGED_BY] [int] NULL,
	[PUBL_DELETED_BY] [int] NULL,
	[PUBL_CREATED] [datetime] NOT NULL,
	[PUBL_CHANGED] [datetime] NULL,
	[PUBL_DELETED] [datetime] NULL,
 CONSTRAINT [PK_PUBLS] PRIMARY KEY CLUSTERED 
(
	[PUBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[PUBLS] ADD  CONSTRAINT [DF_Table_1_LANG_CREATED]  DEFAULT (getdate()) FOR [PUBL_CREATED]
GO


