USE [easyxms]
GO
/****** Object:  Table [dbo].[CONNECTIONS]    Script Date: 13.06.2015 11:38:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONNECTIONS](
	[CONN_ID] [int] IDENTITY(1,1) NOT NULL,
	[CONN_FROM] [int] NULL,
	[CONN_TO] [int] NULL,
	[CONN_TYPE] [int] NULL,
	[CONN_SORT] [int] NULL,
	[CONN_FROM_TYPE] [int] NOT NULL,
	[CONN_TO_TYPE] [int] NOT NULL,
	[CONN_CREATED] [datetime] NOT NULL,
	[CONN_CREATED_BY] [int] NULL,
 CONSTRAINT [PK_CONNECTIONS] PRIMARY KEY CLUSTERED 
(
	[CONN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[CONNECTIONS] ADD  CONSTRAINT [DF_CONNECTIONS_CONN_INDEX]  DEFAULT ((0)) FOR [CONN_SORT]
GO
ALTER TABLE [dbo].[CONNECTIONS] ADD  CONSTRAINT [DF_CONNECTIONS_CONN_CREATED]  DEFAULT (getdate()) FOR [CONN_CREATED]
GO
