USE [easyxms]
GO

/****** Object:  Table [dbo].[APPLS]    Script Date: 01.07.2016 21:51:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APPLS](
	[APPL_ID] [int] NOT NULL,
	[APPL_NAME] [nvarchar](100) NULL,
	[APPL_DESC] [nvarchar](max) NULL,
	[APPL_CREATED_BY] [int] NOT NULL,
	[APPL_CHANGED_BY] [int] NOT NULL,
	[APPL_DELETED_BY] [int] NULL,
	[APPL_CREATED] [datetime] NOT NULL,
	[APPL_CHANGED] [datetime] NOT NULL,
	[APPL_DELETED] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[APPLS] ADD  CONSTRAINT [DF_APPLS_APPL_CREATED]  DEFAULT (getdate()) FOR [APPL_CREATED]
GO

ALTER TABLE [dbo].[APPLS] ADD  CONSTRAINT [DF_APPLS_APPL_CHANGED]  DEFAULT (getdate()) FOR [APPL_CHANGED]
GO


