USE [easyxms]
GO

/****** Object:  Table [dbo].[STNGS]    Script Date: 06.07.2016 17:51:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STNGS](
	[STNG_ID] [int] NOT NULL,
	[STNG_NAME] [nvarchar](100) NOT NULL,
	[STNG_VALUE] [nvarchar](255) NOT NULL,
	[STNG_TYPE] [int] NOT NULL,
	[STNG_CREATED_BY] [int] NOT NULL,
	[STNG_CHANGED_BY] [int] NOT NULL,
	[STNG_DELETED_BY] [int] NULL,
	[STNG_CREATED] [datetime] NOT NULL,
	[STNG_CHANGED] [datetime] NULL,
	[STNG_DELETED] [datetime] NULL,
 CONSTRAINT [PK_STNGS] PRIMARY KEY CLUSTERED 
(
	[STNG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[STNGS] ADD  CONSTRAINT [DF_Table_1_ATOM_CREATED_1]  DEFAULT (getdate()) FOR [STNG_CREATED]
GO