USE [easyxms]
GO

/****** Object:  Table [dbo].[TYPES]    Script Date: 28.06.2016 16:13:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TYPES](
	[TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[TYPE_NAME] [nvarchar](40) NULL,
	[TYPE_SHORTCUT] [nvarchar](4) NULL,
	[TYPE_DESCRIPTION] [ntext] NULL,
	[TYPE_CREATED_BY] [int] NOT NULL,
	[TYPE_CHANGED_BY] [int] NOT NULL,
	[TYPE_DELETED_BY] [int] NULL,
	[TYPE_CREATED] [datetime] NOT NULL,
	[TYPE_CHANGED] [datetime] NOT NULL,
	[TYPE_DELETED] [datetime] NULL,
 CONSTRAINT [PK_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[TYPES] ADD  CONSTRAINT [DF_Table_1_ATOM_CREATED]  DEFAULT (getdate()) FOR [TYPE_CREATED]

GO