USE [easyxms]
GO

/****** Object:  Table [dbo].[CNTNT]    Script Date: 14.07.2016 16:15:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CNTNT](
	[CNTN_ID] [int] NOT NULL,
	[CNTN_TITLE_1] [nvarchar](1000) NULL,
	[CNTN_TITLE_2] [nvarchar](1000) NULL,
	[CNTN_ABSTRACT] [nvarchar](max) NULL,
	[CNTN_TEXT] [nvarchar](max) NULL,
	[CNTN_CREATED_BY] [int] NOT NULL,
	[CNTN_CHANGED_BY] [int] NULL,
	[CNTN_DELETED_BY] [int] NULL,
	[CNTN_CREATED] [datetime] NOT NULL,
	[CNTN_CHANGED] [datetime] NULL,
	[CNTN_DELETED] [datetime] NULL,
 CONSTRAINT [PK_CNTNT] PRIMARY KEY CLUSTERED 
(
	[CNTN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[CNTNT] ADD  CONSTRAINT [DF_Table_1_USER_CREATED_BY]  DEFAULT ((1)) FOR [CNTN_CREATED_BY]
GO

ALTER TABLE [dbo].[CNTNT] ADD  CONSTRAINT [DF_Table_1_USER_CREATED]  DEFAULT (getdate()) FOR [CNTN_CREATED]
GO


