USE [easyxms]
GO

/****** Object:  Table [dbo].[CNTXT]    Script Date: 28.06.2016 16:17:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CNTXT](
	[CNTX_ID] [int] NOT NULL,
	[CNTX_NAME] [nvarchar](100) NULL,
	[CNTX_DESC] [nvarchar](max) NULL,
	[CNTX_CREATED_BY] [int] NOT NULL,
	[CNTX_CHANGED_BY] [int] NOT NULL,
	[CNTX_DELETED_BY] [int] NULL,
	[CNTX_CREATED] [datetime] NOT NULL,
	[CNTX_CHANGED] [datetime] NULL,
	[CNTX_DELETED] [datetime] NULL,
 CONSTRAINT [PK_CNTXT] PRIMARY KEY CLUSTERED 
(
	[CNTX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[CNTXT] ADD  CONSTRAINT [DF_CNTXT_CNTX_CREATED]  DEFAULT (getdate()) FOR [CNTX_CREATED]
GO