USE [easyxms]
GO
/****** Object:  Table [dbo].[ATOMS]    Script Date: 13.06.2015 11:38:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATOMS](
	[ATOM_ID] [int] IDENTITY(1,1) NOT NULL,
	[ATOM_TITLE] [nvarchar](255) NOT NULL,
	[ATOM_SHORT] [nvarchar](2000) NULL,
	[ATOM_TEXT] [ntext] NULL,
	[ATOM_CREATED_BY] [int] NULL,
	[ATOM_CHANGED_BY] [int] NULL,
	[ATOM_DELETED_BY] [int] NULL,
	[ATOM_CREATED] [datetime] NOT NULL,
	[ATOM_CHANGED] [datetime] NULL,
	[ATOM_DELETED] [datetime] NULL,
 CONSTRAINT [PK_ATOMS] PRIMARY KEY CLUSTERED 
(
	[ATOM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[ATOMS] ADD  CONSTRAINT [DF_ATOMS_ATOM_CREATED]  DEFAULT (getdate()) FOR [ATOM_CREATED]
GO
