USE [easyxms]
GO

/****** Object:  Table [dbo].[ATTRS]    Script Date: 28.06.2016 16:16:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ATTRS](
	[ATTR_ID] [int] NOT NULL,
	[ATTR_SHORT] [nvarchar](255) NULL,
	[ATTR_INT] [int] NULL,
	[ATTR_DATE] [datetime] NULL,
	[ATTR_NUM] [numeric](18, 0) NULL,
	[ATTR_TEXT] [nvarchar](max) NULL,
	[ATTR_TYPE_ID] [int] NULL,
	[ATTR_CREATED_BY] [int] NOT NULL,
	[ATTR_CHANGED_BY] [int] NOT NULL,
	[ATTR_DELETED_BY] [int] NULL,
	[ATTR_CREATED] [datetime] NOT NULL,
	[ATTR_CHANGED] [datetime] NULL,
	[ATTR_DELETED] [datetime] NULL,
 CONSTRAINT [PK_ATTRS] PRIMARY KEY CLUSTERED 
(
	[ATTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[ATTRS] ADD  CONSTRAINT [DF_ATTRS_ATTR_CREATED]  DEFAULT (getdate()) FOR [ATTR_CREATED]
GO