USE [easyxms]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 28.06.2016 16:13:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
	[USER_ID] [int] NOT NULL,
	[USER_NAME] [nvarchar](25) NOT NULL,
	[USER_PASSWORD] [nvarchar](200) NOT NULL,
	[USER_NAMEFIRST] [nvarchar](100) NULL,
	[USER_NAMELAST] [nvarchar](100) NULL,
	[USER_EMAILADRESS] [nvarchar](100) NULL,
	[USER_CREATED_BY] [int] NOT NULL,
	[USER_CHANGED_BY] [int] NOT NULL,
	[USER_DELETED_BY] [int] NULL,
	[USER_CREATED] [datetime] NOT NULL,
	[USER_CHANGED] [datetime] NOT NULL,
	[USER_DELETED] [datetime] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_USER_CREATED_BY]  DEFAULT ((1)) FOR [USER_CREATED_BY]
GO

ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_USER_CHANGED_BY]  DEFAULT ((1)) FOR [USER_CHANGED_BY]
GO

ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_ROLE_CREATED]  DEFAULT (getdate()) FOR [USER_CREATED]
GO


