USE [easyxms]
GO
/****** Object:  Table [dbo].[APPLS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APPLS](
	[APPL_ID] [int] NOT NULL,
	[APPL_NAME] [nvarchar](100) NULL,
	[APPL_DESC] [nvarchar](max) NULL,
	[APPL_CREATED_BY] [int] NOT NULL,
	[APPL_CHANGED_BY] [int] NOT NULL,
	[APPL_DELETED_BY] [int] NULL,
	[APPL_CREATED] [datetime] NOT NULL,
	[APPL_CHANGED] [datetime] NOT NULL,
	[APPL_DELETED] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ATOMS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATOMS](
	[ATOM_ID] [int] NOT NULL,
	[ATOM_TITLE] [nvarchar](255) NOT NULL,
	[ATOM_SHORT] [nvarchar](2000) NULL,
	[ATOM_TEXT] [nvarchar](max) NULL,
	[ATOM_CREATED_BY] [int] NOT NULL,
	[ATOM_CHANGED_BY] [int] NOT NULL,
	[ATOM_DELETED_BY] [int] NULL,
	[ATOM_CREATED] [datetime] NOT NULL,
	[ATOM_CHANGED] [datetime] NULL,
	[ATOM_DELETED] [datetime] NULL,
 CONSTRAINT [PK_ATOMS] PRIMARY KEY CLUSTERED 
(
	[ATOM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ATTRS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATTRS](
	[ATTR_ID] [int] NOT NULL,
	[ATTR_SHORT] [nvarchar](255) NULL,
	[ATTR_INT] [int] NULL,
	[ATTR_DATE] [datetime] NULL,
	[ATTR_NUM] [numeric](18, 0) NULL,
	[ATTR_TEXT] [nvarchar](max) NULL,
	[ATTR_TYPE_ID] [int] NULL,
	[ATTR_CREATED_BY] [int] NOT NULL,
	[ATTR_CHANGED_BY] [int] NOT NULL,
	[ATTR_DELETED_BY] [int] NULL,
	[ATTR_CREATED] [datetime] NOT NULL,
	[ATTR_CHANGED] [datetime] NULL,
	[ATTR_DELETED] [datetime] NULL,
 CONSTRAINT [PK_ATTRS] PRIMARY KEY CLUSTERED 
(
	[ATTR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CNTNT]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNTNT](
	[CNTN_ID] [int] NOT NULL,
	[CNTN_TITLE_1] [nvarchar](1000) NULL,
	[CNTN_TITLE_2] [nvarchar](1000) NULL,
	[CNTN_ABSTRACT] [nvarchar](max) NULL,
	[CNTN_TEXT] [nvarchar](max) NULL,
	[CNTN_CREATED_BY] [int] NOT NULL,
	[CNTN_CHANGED_BY] [int] NULL,
	[CNTN_DELETED_BY] [int] NULL,
	[CNTN_CREATED] [datetime] NOT NULL,
	[CNTN_CHANGED] [datetime] NULL,
	[CNTN_DELETED] [datetime] NULL,
 CONSTRAINT [PK_CNTNT] PRIMARY KEY CLUSTERED 
(
	[CNTN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CNTXT]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNTXT](
	[CNTX_ID] [int] NOT NULL,
	[CNTX_NAME] [nvarchar](100) NULL,
	[CNTX_DESC] [nvarchar](max) NULL,
	[CNTX_CREATED_BY] [int] NOT NULL,
	[CNTX_CHANGED_BY] [int] NULL,
	[CNTX_DELETED_BY] [int] NULL,
	[CNTX_CREATED] [datetime] NOT NULL,
	[CNTX_CHANGED] [datetime] NULL,
	[CNTX_DELETED] [datetime] NULL,
 CONSTRAINT [PK_CNTXT] PRIMARY KEY CLUSTERED 
(
	[CNTX_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[CONNS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONNS](
	[CONN_ID] [int] IDENTITY(1,1) NOT NULL,
	[CONN_FROM] [int] NULL,
	[CONN_TO] [int] NULL,
	[CONN_TYPE] [int] NULL,
	[CONN_SORT] [int] NULL,
	[CONN_FROM_TYPE] [int] NOT NULL,
	[CONN_TO_TYPE] [int] NOT NULL,
	[CONN_CREATED] [datetime] NOT NULL,
	[CONN_CREATED_BY] [int] NULL,
 CONSTRAINT [PK_CONNECTIONS] PRIMARY KEY CLUSTERED 
(
	[CONN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LANGS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LANGS](
	[LANG_ID] [int] NOT NULL,
	[LANG_NAME] [nvarchar](100) NULL,
	[LANG_DESC] [nvarchar](max) NULL,
	[LANG_CREATED_BY] [int] NULL,
	[LANG_CHANGED_BY] [int] NULL,
	[LANG_DELETED_BY] [int] NULL,
	[LANG_CREATED] [datetime] NOT NULL,
	[LANG_CHANGED] [datetime] NULL,
	[LANG_DELETED] [datetime] NULL,
 CONSTRAINT [PK_LANGS] PRIMARY KEY CLUSTERED 
(
	[LANG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PUBLS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLS](
	[PUBL_ID] [int] NOT NULL,
	[PUBL_NAME] [nvarchar](100) NULL,
	[PUBL_DESC] [nvarchar](max) NULL,
	[PUBL_CREATED_BY] [int] NULL,
	[PUBL_CHANGED_BY] [int] NULL,
	[PUBL_DELETED_BY] [int] NULL,
	[PUBL_CREATED] [datetime] NOT NULL,
	[PUBL_CHANGED] [datetime] NULL,
	[PUBL_DELETED] [datetime] NULL,
 CONSTRAINT [PK_PUBLS] PRIMARY KEY CLUSTERED 
(
	[PUBL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[ROLE_ID] [int] NOT NULL,
	[ROLE_NAME] [nvarchar](100) NULL,
	[ROLE_CREATED_BY] [int] NULL,
	[ROLE_CHANGED_BY] [int] NULL,
	[ROLE_DELETED_BY] [int] NULL,
	[ROLE_CREATED] [datetime] NOT NULL,
	[ROLE_CHANGED] [datetime] NULL,
	[ROLE_DELETED] [datetime] NULL,
 CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[STNGS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STNGS](
	[STNG_ID] [int] NOT NULL,
	[STNG_NAME] [nvarchar](100) NOT NULL,
	[STNG_VALUE] [nvarchar](255) NOT NULL,
	[STNG_TYPE] [int] NOT NULL,
	[STNG_CREATED_BY] [int] NOT NULL,
	[STNG_CHANGED_BY] [int] NOT NULL,
	[STNG_DELETED_BY] [int] NULL,
	[STNG_CREATED] [datetime] NOT NULL,
	[STNG_CHANGED] [datetime] NULL,
	[STNG_DELETED] [datetime] NULL,
 CONSTRAINT [PK_STNGS] PRIMARY KEY CLUSTERED 
(
	[STNG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TYPES]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TYPES](
	[TYPE_ID] [int] NOT NULL,
	[TYPE_NAME] [nvarchar](40) NULL,
	[TYPE_SHORTCUT] [nvarchar](4) NULL,
	[TYPE_DESCRIPTION] [ntext] NULL,
	[TYPE_CREATED_BY] [int] NOT NULL CONSTRAINT [DF_TYPES_TYPE_CREATED_BY]  DEFAULT ((1)),
	[TYPE_CHANGED_BY] [int] NULL,
	[TYPE_DELETED_BY] [int] NULL,
	[TYPE_CREATED] [datetime] NOT NULL CONSTRAINT [DF_Table_1_ATOM_CREATED]  DEFAULT (getdate()),
	[TYPE_CHANGED] [datetime] NULL,
	[TYPE_DELETED] [datetime] NULL,
 CONSTRAINT [PK_TYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[USERS]    Script Date: 01.07.2016 21:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[USER_ID] [int] NOT NULL,
	[USER_NAME] [nvarchar](25) NOT NULL,
	[USER_PASSWORD] [nvarchar](200) NOT NULL,
	[USER_NAMEFIRST] [nvarchar](100) NULL,
	[USER_NAMELAST] [nvarchar](100) NULL,
	[USER_EMAILADRESS] [nvarchar](100) NULL,
	[USER_CREATED_BY] [int] NOT NULL,
	[USER_CHANGED_BY] [int] NOT NULL,
	[USER_DELETED_BY] [int] NULL,
	[USER_CREATED] [datetime] NOT NULL,
	[USER_CHANGED] [datetime] NULL,
	[USER_DELETED] [datetime] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[APPLS] ADD  CONSTRAINT [DF_APPLS_APPL_CREATED]  DEFAULT (getdate()) FOR [APPL_CREATED]
GO
ALTER TABLE [dbo].[APPLS] ADD  CONSTRAINT [DF_APPLS_APPL_CHANGED]  DEFAULT (getdate()) FOR [APPL_CHANGED]
GO
ALTER TABLE [dbo].[ATOMS] ADD  CONSTRAINT [DF_ATOMS_ATOM_CREATED]  DEFAULT (getdate()) FOR [ATOM_CREATED]
GO
ALTER TABLE [dbo].[ATTRS] ADD  CONSTRAINT [DF_ATTRS_ATTR_CREATED]  DEFAULT (getdate()) FOR [ATTR_CREATED]
GO
ALTER TABLE [dbo].[CNTNT] ADD  CONSTRAINT [DF_CNTNT_USER_CREATED_BY]  DEFAULT ((1)) FOR [CNTN_CREATED_BY]
GO
ALTER TABLE [dbo].[CNTNT] ADD  CONSTRAINT [DF_CNTNT_USER_CREATED]  DEFAULT (getdate()) FOR [CNTN_CREATED]
GO
ALTER TABLE [dbo].[CNTXT] ADD  CONSTRAINT [DF_CNTXT_CNTX_CREATED]  DEFAULT (getdate()) FOR [CNTX_CREATED]
GO
ALTER TABLE [dbo].[CONNS] ADD  CONSTRAINT [DF_CONNECTIONS_CONN_SORT]  DEFAULT ((0)) FOR [CONN_SORT]
GO
ALTER TABLE [dbo].[CONNS] ADD  CONSTRAINT [DF_CONNECTIONS_CONN_CREATED]  DEFAULT (getdate()) FOR [CONN_CREATED]
GO
ALTER TABLE [dbo].[LANGS] ADD  CONSTRAINT [DF_LANGS_LNGU_CREATED]  DEFAULT (getdate()) FOR [LANG_CREATED]
GO
ALTER TABLE [dbo].[PUBLS] ADD  CONSTRAINT [DF_PUBLS_PUBL_CREATED]  DEFAULT (getdate()) FOR [PUBL_CREATED]
GO
ALTER TABLE [dbo].[ROLES] ADD  CONSTRAINT [DF_ROLES_ROLE_CREATED]  DEFAULT (getdate()) FOR [ROLE_CREATED]
GO
ALTER TABLE [dbo].[STNGS] ADD  CONSTRAINT [DF_STNGS_STNG_CREATED]  DEFAULT (getdate()) FOR [STNG_CREATED]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_USER_CREATED_BY]  DEFAULT ((1)) FOR [USER_CREATED_BY]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_USER_CHANGED_BY]  DEFAULT ((1)) FOR [USER_CHANGED_BY]
GO
ALTER TABLE [dbo].[USERS] ADD  CONSTRAINT [DF_USERS_ROLE_CREATED]  DEFAULT (getdate()) FOR [USER_CREATED]
GO
